/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AjouterAchat;

import Data.Client;
import Data.Produit;
import Data.TableClient;
import Data.TableProduit;
import Facture.Facture;
import Menuclient.Model_Card;
import Supprimer.Option;
import Table.ScrollBar;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monta
 */
public class AjouterAchat extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterAchat
     */
    Connection con;
PreparedStatement pst;
ResultSet rs;






public void conect() throws SQLException, ClassNotFoundException{
    Class.forName("org.sqlite.JDBC");
 con=DriverManager.getConnection("jdbc:sqlite:data.db");
} 
void Table4(){
     String[] client= {"ID_PRODUIT","NOM_PRODUIT","PRIX","QANTITE"};
       String [] afficher =new String[4];
       DefaultTableModel model = new DefaultTableModel(null,client);
       try{
           conect();
        Statement st=(Statement) con.createStatement() ;      
        rs = st.executeQuery(" select ID_PRODUIT,NOM_PRODUIT,PRIX,QANTITE from PRODUIT,ACHAT,DATE_ACHAT where ACHAT.CODE_CLIENT="+txtid_client.getText()+"  and ACHAT.ID_ACHAT= (select max(ID_ACHAT) from achat)  and ACHAT.ID_ACHAT=DATE_ACHAT.IDACHAT and DATE_ACHAT.IDPRODUIT=produit.ID_PRODUIT");
             while(rs.next()){
           afficher[0]=rs.getString("ID_PRODUIT");
           afficher[1]=rs.getString("NOM_PRODUIT");
           afficher[2]=rs.getString("PRIX")+"   TND";
           afficher[3]=rs.getString("QANTITE");  
           model.addRow(afficher);
       }
       table1.setModel(model);
    
               con.close();
       }catch(Exception e){e.printStackTrace();
       }
}

    void Table3(){
     String[] client= {"ID_PRODUIT","NOM_PRODUIT","PRIX","QANTITE"};
       String [] afficher =new String[4];
       DefaultTableModel model = new DefaultTableModel(null,client);
        table1.setModel(model);}

 public void dimnuerStoke(int stokedimuner,int codeproduit)throws Exception{
   
            int stoke = 0;
            conect();
            Statement st=(Statement) con.createStatement() ;
            rs = st.executeQuery("select stoke from produit where ID_PRODUIT= "+codeproduit);
            while(rs.next()){
                stoke=rs.getInt("stoke");            }
            if(stoke >=stokedimuner ){            
            stoke=stoke-stokedimuner;
            String sql=" update PRODUIT set stoke ="+stoke+" where ID_PRODUIT= '"+codeproduit+"' ";
            pst=con.prepareStatement(sql);
            pst.execute();
            con.close();}
            else {
                
                Option o =new Option("STOKE INSUFFISANT LE STOKE RESTE EST "+stoke);
              o.main(" STOKE INSUFFISANT LE STOKE RESTE EST "+stoke);
                throw new Exception();
                 }
}
        


    public AjouterAchat() {
        initComponents();
         card2.setData(new Model_Card(new ImageIcon(getClass().getResource("/com/raven/icon/achat.png")), "Ajouter Achat", "", ""));
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        jScrollPane1.getVerticalScrollBar().setBackground(Color.WHITE);
        jScrollPane1.getViewport().setBackground(new Color(36,36,77));
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        jPanel1.setVisible(false);
          jPanel2.setVisible(false);
            jPanel3.setVisible(false);
              jPanel4.setVisible(false);
        Table3();
        TableProduit p =new TableProduit();
        DefaultComboBoxModel tab =new DefaultComboBoxModel();
        for(Produit pr : p.getTable())
            tab.addElement(pr.getId()+"  "+pr.getNom());
      txtidproduit2.setModel(tab);
    
    }
    
public int getId(){
  String str = (String) txtidproduit2.getSelectedItem();
        String[] words = str.split(" ");
      
return Integer.parseInt(words[0]);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degrade1 = new swing.degrade();
        panelBorder3 = new swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new Menuclient.Table();
        jLabel6 = new javax.swing.JLabel();
        panelBorder1 = new swing.PanelBorder();
        panelBorder2 = new swing.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        txtid_client = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtquantite = new javax.swing.JTextField();
        buttonBadges3 = new swing.ButtonBadges();
        buttonBadges2 = new swing.ButtonBadges();
        buttonBadges1 = new swing.ButtonBadges();
        txtidproduit2 = new combo_suggestion.ComboBoxSuggestion();
        jPanel4 = new javax.swing.JPanel();
        kButton4 = new swing.KButton();
        kButton6 = new swing.KButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtnontanttotale = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnomproduit4 = new javax.swing.JTextField();
        kButton5 = new swing.KButton();
        card2 = new swing.cardbuton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtnomproduit6 = new javax.swing.JTextField();
        kButton2 = new swing.KButton();

        setResizable(true);

        degrade1.setPreferredSize(new java.awt.Dimension(1094, 774));

        panelBorder3.setBackground(new java.awt.Color(36, 36, 77));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        table1.setBackground(new java.awt.Color(36, 36, 77));
        table1.setForeground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table1);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 141, 24));
        jLabel6.setText("Ajouter Un Achat");

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(140, 122, 230));
        jLabel2.setText("ID Client");
        panelBorder2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, -1, -1));

        txtid_client.setBackground(new java.awt.Color(242, 242, 242));
        txtid_client.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txtid_client.setForeground(new java.awt.Color(102, 102, 102));
        txtid_client.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(140, 122, 230)));
        txtid_client.setVerifyInputWhenFocusTarget(false);
        txtid_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_clientActionPerformed(evt);
            }
        });
        panelBorder2.add(txtid_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, 180, 24));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(140, 122, 230));
        jLabel1.setText("Produit");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        jLabel3.setForeground(new java.awt.Color(140, 122, 230));
        jLabel3.setText("Quantité");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 62, -1, -1));

        txtquantite.setBackground(new java.awt.Color(242, 242, 242));
        txtquantite.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txtquantite.setForeground(new java.awt.Color(102, 102, 102));
        txtquantite.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(140, 122, 230)));
        txtquantite.setVerifyInputWhenFocusTarget(false);
        txtquantite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantiteActionPerformed(evt);
            }
        });
        jPanel1.add(txtquantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 210, 24));

        buttonBadges3.setBackground(new java.awt.Color(255, 102, 102));
        buttonBadges3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/annuler.png"))); // NOI18N
        buttonBadges3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges3ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBadges3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, 66, 47));

        buttonBadges2.setBackground(new java.awt.Color(0, 204, 51));
        buttonBadges2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/acheter.png"))); // NOI18N
        buttonBadges2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges2ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBadges2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 114, 66, 47));

        buttonBadges1.setBackground(new java.awt.Color(255, 0, 51));
        buttonBadges1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/achats.png"))); // NOI18N
        buttonBadges1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBadges1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 114, 66, 47));

        txtidproduit2.setBorder(null);
        txtidproduit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidproduit2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtidproduit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 24));

        panelBorder2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 190));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton4.setForeground(new java.awt.Color(140, 122, 230));
        kButton4.setText("Imprimer");
        kButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton4.setkEndColor(new java.awt.Color(224, 255, 255));
        kButton4.setkFillButton(false);
        kButton4.setkForeGround(new java.awt.Color(140, 122, 230));
        kButton4.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        kButton4.setkHoverForeGround(new java.awt.Color(224, 255, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(224, 255, 255));
        kButton4.setkSelectedColor(new java.awt.Color(204, 204, 255));
        kButton4.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 157, -1));

        kButton6.setText("Fin Achat");
        kButton6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton6.setkEndColor(new java.awt.Color(224, 255, 255));
        kButton6.setkFillButton(false);
        kButton6.setkForeGround(new java.awt.Color(140, 122, 230));
        kButton6.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        kButton6.setkHoverForeGround(new java.awt.Color(224, 255, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(224, 255, 255));
        kButton6.setkSelectedColor(new java.awt.Color(204, 204, 255));
        kButton6.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 157, -1));

        panelBorder2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(140, 122, 230));
        jLabel7.setText("Montant Totale");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, -1, -1));

        txtnontanttotale.setBackground(new java.awt.Color(242, 242, 242));
        txtnontanttotale.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txtnontanttotale.setForeground(new java.awt.Color(102, 102, 102));
        txtnontanttotale.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(140, 122, 230)));
        txtnontanttotale.setEnabled(false);
        txtnontanttotale.setVerifyInputWhenFocusTarget(false);
        txtnontanttotale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnontanttotaleActionPerformed(evt);
            }
        });
        jPanel3.add(txtnontanttotale, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 182, 24));

        jLabel8.setForeground(new java.awt.Color(140, 122, 230));
        jLabel8.setText("Montant Reste");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, -1, -1));

        txtnomproduit4.setBackground(new java.awt.Color(242, 242, 242));
        txtnomproduit4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txtnomproduit4.setForeground(new java.awt.Color(102, 102, 102));
        txtnomproduit4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(140, 122, 230)));
        txtnomproduit4.setEnabled(false);
        txtnomproduit4.setVerifyInputWhenFocusTarget(false);
        txtnomproduit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomproduit4ActionPerformed(evt);
            }
        });
        jPanel3.add(txtnomproduit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, 182, 24));

        kButton5.setText("Enregistre");
        kButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        kButton5.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton5.setkEndColor(new java.awt.Color(224, 255, 255));
        kButton5.setkFillButton(false);
        kButton5.setkForeGround(new java.awt.Color(140, 122, 230));
        kButton5.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        kButton5.setkHoverForeGround(new java.awt.Color(224, 255, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(224, 255, 255));
        kButton5.setkSelectedColor(new java.awt.Color(204, 204, 255));
        kButton5.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, -1, -1));

        panelBorder2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 167));

        card2.setColor1(new java.awt.Color(51, 51, 255));
        card2.setColor2(new java.awt.Color(153, 0, 51));
        card2.setkBackGroundColor(new java.awt.Color(204, 0, 204));
        card2.setkEndColor(new java.awt.Color(0, 102, 102));
        card2.setkHoverEndColor(new java.awt.Color(0, 51, 255));
        card2.setkHoverForeGround(new java.awt.Color(51, 255, 255));
        card2.setkHoverStartColor(new java.awt.Color(204, 204, 255));
        card2.setkPressedColor(new java.awt.Color(204, 255, 204));
        card2.setkSelectedColor(new java.awt.Color(153, 255, 255));
        card2.setkStartColor(new java.awt.Color(204, 255, 255));
        card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card2MouseClicked(evt);
            }
        });
        panelBorder2.add(card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 220));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/panier.png"))); // NOI18N
        panelBorder2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, -1));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(140, 122, 230));
        jLabel4.setText("Montant Deposer");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        txtnomproduit6.setBackground(new java.awt.Color(242, 242, 242));
        txtnomproduit6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        txtnomproduit6.setForeground(new java.awt.Color(102, 102, 102));
        txtnomproduit6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(140, 122, 230)));
        txtnomproduit6.setVerifyInputWhenFocusTarget(false);
        txtnomproduit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomproduit6ActionPerformed(evt);
            }
        });
        jPanel2.add(txtnomproduit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 197, 24));

        kButton2.setText("Calculer le reste");
        kButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(51, 102, 255));
        kButton2.setkEndColor(new java.awt.Color(224, 255, 255));
        kButton2.setkFillButton(false);
        kButton2.setkForeGround(new java.awt.Color(140, 122, 230));
        kButton2.setkHoverEndColor(new java.awt.Color(0, 153, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(224, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(224, 255, 255));
        kButton2.setkSelectedColor(new java.awt.Color(204, 204, 255));
        kButton2.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 197, -1));

        panelBorder2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 167));

        panelBorder1.add(panelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 990, 310));

        javax.swing.GroupLayout degrade1Layout = new javax.swing.GroupLayout(degrade1);
        degrade1.setLayout(degrade1Layout);
        degrade1Layout.setHorizontalGroup(
            degrade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(degrade1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(degrade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        degrade1Layout.setVerticalGroup(
            degrade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, degrade1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(degrade1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(degrade1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void card2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card2MouseClicked
txtid_client.setEnabled(false);
 card2.setVisible(false);
     jPanel1.setVisible(true);
       try {
           conect();
            String sql="insert into ACHAT(DATE_ACHAT,CODE_CLIENT) values (current_date,?)";
            pst=con.prepareStatement(sql);
 
            pst.setString(1,txtid_client.getText());
            pst.execute();
            con.close();
           } catch (Exception e) {   JOptionPane.showConfirmDialog(null, "ERREUR");
            
          txtnomproduit4.setText(null);
       txtnomproduit6.setText(null);
       txtnontanttotale.setText(null);    
       txtid_client.setText(null);
      
       Table3();
        }
    }//GEN-LAST:event_card2MouseClicked

    private void txtidproduit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidproduit2ActionPerformed
       
    }//GEN-LAST:event_txtidproduit2ActionPerformed

    private void txtid_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_clientActionPerformed

    private void txtquantiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantiteActionPerformed

    private void txtnomproduit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomproduit6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomproduit6ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
     jPanel3.setVisible(true);
        float x;
        x=Float.parseFloat(   txtnomproduit6.getText()) - Float.parseFloat(   txtnontanttotale.getText()) ;
        txtnomproduit4.setText(Float.toString(x));
      
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
     
        try {     conect();
        Statement st=(Statement) con.createStatement() ;      
        rs = st.executeQuery("SELECT MAX(ID_ACHAT) FROM ACHAT");
       String id = null;
        while(rs.next())
           id=rs.getString("MAX(ID_ACHAT)");
         TableClient tabe =new TableClient();
      Client c=tabe.getClient(Integer.parseInt(txtid_client.getText()));
      Facture  facture =new Facture(id, Integer.toString(c.getId()), table1, c.getNom(), Integer.toString(c.getTelephone()), txtnontanttotale.getText(), txtnomproduit6.getText(), txtnomproduit4.getText());
      facture.imprimer();
        } catch (Exception e) {
        }
      
      
      
       
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
   jPanel4.setVisible(true);
        
        float x=Float.parseFloat(txtnomproduit4.getText());
      if(x<0){ 
          try {
            conect();
            String sql="update ACHAT set MONTANT_TOTALE= "+txtnontanttotale.getText()+", MONTANT_DEPOSER="+txtnomproduit6.getText()+" , MONTENT_RESTE = "+x+" ,DATE_ACHAT = current_date where ID_ACHAT= (select max(ID_ACHAT) from achat) and CODE_CLIENT= "+txtid_client.getText()+"  ";
            pst=con.prepareStatement(sql);
            pst.execute();
           con.close();
             Option o =new Option("ENRESTREMENT REUSSI");
              o.main("ENRESTREMENT REUSSI");
        } catch (Exception e) {   
           Option o =new Option("ENRESTREMENT ERREUR");
              o.main("ENRESTREMENT ERREUR");}
    }
      else{
           try {
            conect();
            String sql="update ACHAT set MONTANT_TOTALE= "+txtnontanttotale.getText()+", MONTANT_DEPOSER="+txtnontanttotale.getText()+" , MONTENT_RESTE = 0 ,DATE_ACHAT = current_date where ID_ACHAT= (select max(ID_ACHAT) from achat)  and CODE_CLIENT= "+txtid_client.getText()+"  ";
            pst=con.prepareStatement(sql);
            pst.execute();   
            con.close();
         Option o =new Option("ENRESTREMENT REUSSI");
              o.main("ENRESTREMENT REUSSI");
        } catch (Exception e) {   
           Option o =new Option("ENRESTREMENT ERREUR");
              o.main("ENRESTREMENT ERREUR");}
      
      }
    }//GEN-LAST:event_kButton5ActionPerformed

    private void txtnontanttotaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnontanttotaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnontanttotaleActionPerformed

    private void txtnomproduit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomproduit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomproduit4ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
  jPanel2.setVisible(false); 
        jPanel4.setVisible(false); card2.setVisible(true);
       txtid_client.setEnabled(true);
     txtid_client.setEnabled(true);
     txtid_client.setText(null);
     jPanel2.setVisible(false); 
        jPanel3.setVisible(false);
     Table3();
    }//GEN-LAST:event_kButton6ActionPerformed

    private void buttonBadges1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges1ActionPerformed
      jPanel1.setVisible(false);
       jPanel2.setVisible(true);
               
        float somme=0;
        
        try{
           conect();
        Statement st=(Statement) con.createStatement() ;      
        rs = st.executeQuery("select PRIX,QANTITE from PRODUIT,ACHAT,DATE_ACHAT where ACHAT.CODE_CLIENT="+txtid_client.getText()+"  and ACHAT.ID_ACHAT= (select max(ID_ACHAT) from achat)  and ACHAT.ID_ACHAT=DATE_ACHAT.IDACHAT and DATE_ACHAT.IDPRODUIT=produit.ID_PRODUIT");
            
        while(rs.next()){
           somme=rs.getFloat("PRIX")  * rs.getInt("QANTITE")+somme;}   
             con.close();
         txtnontanttotale.setText(Float.toString(somme));
       
       }catch(Exception e){e.printStackTrace();
       }      
                                             

      
    }//GEN-LAST:event_buttonBadges1ActionPerformed

    private void buttonBadges2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges2ActionPerformed
               try {
             int stoke;
             stoke=Integer.parseInt(txtquantite.getText());
           dimnuerStoke(stoke, getId()); 
             conect();
        Statement st=(Statement) con.createStatement() ;      
        rs = st.executeQuery("SELECT MAX(ID_ACHAT) FROM ACHAT");
       String id = null;
        while(rs.next())
           id=rs.getString("MAX(ID_ACHAT)");

            String sql="insert into DATE_ACHAT(IDACHAT,IDPRODUIT,QANTITE) values(?,?,?)";
            pst=con.prepareStatement(sql);
            pst.setString(1,id);
             pst.setInt(2,getId());
            pst.setString(3,txtquantite.getText());
         
            pst.execute();
            con.close();
           Table4();
          
           txtquantite.setText(null);
         } catch (Exception e) { e.printStackTrace();   Option o =new Option(" ERREUR");
              o.main(" ERREUR");
        }

    }//GEN-LAST:event_buttonBadges2ActionPerformed

    private void buttonBadges3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges3ActionPerformed
        txtquantite.setText(null);
    }//GEN-LAST:event_buttonBadges3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonBadges buttonBadges1;
    private swing.ButtonBadges buttonBadges2;
    private swing.ButtonBadges buttonBadges3;
    private swing.cardbuton card2;
    private swing.degrade degrade1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.KButton kButton2;
    private swing.KButton kButton4;
    private swing.KButton kButton5;
    private swing.KButton kButton6;
    private swing.PanelBorder panelBorder1;
    private swing.PanelBorder panelBorder2;
    private swing.PanelBorder panelBorder3;
    private Menuclient.Table table1;
    private javax.swing.JTextField txtid_client;
    private combo_suggestion.ComboBoxSuggestion txtidproduit2;
    private javax.swing.JTextField txtnomproduit4;
    private javax.swing.JTextField txtnomproduit6;
    private javax.swing.JTextField txtnontanttotale;
    private javax.swing.JTextField txtquantite;
    // End of variables declaration//GEN-END:variables
}
