/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clientdetailler;

import Data.Achat;
import Data.Client;
import Data.Produit;
import Data.TableAchat;
import Data.TableClient;
import Data.TableProduit;
import Menuclient.TableActionCellEditor;
import Menuclient.TableActionCellRender;
import Menuclient.TableActionEvent;
import Modifier.ModifierProduit;
import Modifier.Modifierachat;
import Modifier.Modifierclient;
import Supprimer.SupprimerAchat;
import Supprimer.SupprimerClient;
import Supprimer.SupprimerProduit;
import Table.ScrollBar;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monta
 */
public class menudetailer extends javax.swing.JFrame {

    int id;
    String nom;
    String numtel;
     void Afficher(){
         TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                Modifierachat mo =new Modifierachat(table1.valusId(row),id);
                mo.main(table1.valusId(row),id);
            }

            @Override
            public void onDelete(int row) {
                if (table1.isEditing()) {
                    table1.getCellEditor().stopCellEditing();
                }
                SupprimerAchat  sup =new SupprimerAchat(table1.valusId(row),id);
              sup.main(table1.valusId(row),id);
                    
            }

            @Override
            public void onView(int row) {
               jLabel1.setText("Achat "+table1.valusId(row));
                Achat ach =new Achat(table1.valusId(row),0.0,0.0,0.0,"",id);
           table1.setModel(ach.Table2(table1.valusId(row), id));
           buttonBadges3.setVisible(false);
           buttonBadges4.setVisible(true);
          
          
            }
        };
           jScrollPane1.setVerticalScrollBar(new ScrollBar());
        jScrollPane1.getVerticalScrollBar().setBackground(Color.WHITE);
        jScrollPane1.getViewport().setBackground(new Color(36,36,77));
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        jScrollPane1.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        p.setBackground(new Color(36,36,77));
        String[] mod ={ "ID Achat", "Montant Totale","Montant Deposer","Montant Reste","Date Achat","Action"};
        DefaultTableModel model = new DefaultTableModel(null,mod); 
         TableAchat ach =new TableAchat(); 
          
        for ( Achat c : ach.rechrcheAchatClient(id)) {
        model.addRow(new Object[]{c.getID_ACHAT(), c.getMONTANT_TOTALE(), c.getMONTANT_DEPOSER(),c.getMONTENT_RESTE(),c.getDATE_ACHAT()});
            }    table1.setModel(model);   
  table1.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
        table1.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(event));    
        }  
    
  void calculer(){ 
      jLabel1.setText("Menu Achat ");
      TableClient lo =new TableClient();
    Client c=lo.getClient(id);
       txtID.setText(Integer.toString(id));
       txtTel.setText(Integer.toString(c.getTelephone()));
        txtnom.setText(c.getNom());
      TableAchat a=new TableAchat();
       txtTotoal.setText(a.sommeMONTANT_TOTALEClient(id)+"  TND");
       txtdeposer.setText(a.sommeMONTANT_DEPOSERClient(id)+"  TND");
       txtreste.setText(a.sommeMONTANT_resteClient(id)+ " TND");}
   
    public menudetailer( int id) {
      initComponents();
        this.id=id;
      setBackground(new Color(0,0,0,0));
      Afficher();
      calculer();
        buttonBadges4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder3 = new swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new Menuclient.Table();
        buttonBadges4 = new swing.ButtonBadges();
        buttonBadges3 = new swing.ButtonBadges();
        panelBorder2 = new swing.PanelBorder();
        imageAvatar1 = new swing.ImageAvatar();
        txtnom = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtreste = new javax.swing.JLabel();
        txtTel = new javax.swing.JLabel();
        txtTotoal = new javax.swing.JLabel();
        txtdeposer = new javax.swing.JLabel();
        panelBorder4 = new swing.PanelBorder();
        buttonBadges1 = new swing.ButtonBadges();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelBorder3.setBackground(new java.awt.Color(36, 36, 77));
        panelBorder3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 141, 24), 3));
        panelBorder3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 141, 24));
        jLabel1.setText("Menu Achat ");
        panelBorder3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        jScrollPane1.setBorder(null);

        table1.setBackground(new java.awt.Color(36, 36, 77));
        table1.setForeground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table1);

        panelBorder3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 730, 400));

        buttonBadges4.setBackground(new java.awt.Color(242, 141, 24));
        buttonBadges4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/contour-du-bouton-circulaire-fleche-arriere-gauche.png"))); // NOI18N
        buttonBadges4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges4ActionPerformed(evt);
            }
        });
        panelBorder3.add(buttonBadges4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 42, 36));

        buttonBadges3.setBackground(new java.awt.Color(242, 141, 24));
        buttonBadges3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/refresh (1).png"))); // NOI18N
        buttonBadges3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges3ActionPerformed(evt);
            }
        });
        panelBorder3.add(buttonBadges3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 42, 36));

        panelBorder2.setBackground(new java.awt.Color(242, 141, 24));
        panelBorder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/man.png"))); // NOI18N
        panelBorder2.add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, 160));

        txtnom.setBackground(new java.awt.Color(255, 255, 255));
        txtnom.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtnom.setForeground(new java.awt.Color(36, 36, 77));
        txtnom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnom.setText("Montassar Tayachi");
        panelBorder2.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 262, 42));

        txtID.setForeground(new java.awt.Color(36, 36, 77));
        txtID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtID.setText("   50");
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(36, 36, 77))); // NOI18N
        panelBorder2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 40));

        txtreste.setForeground(new java.awt.Color(36, 36, 77));
        txtreste.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtreste.setText("  58605647");
        txtreste.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Montant Reste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(36, 36, 77))); // NOI18N
        panelBorder2.add(txtreste, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 160, 40));

        txtTel.setForeground(new java.awt.Color(36, 36, 77));
        txtTel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTel.setText("  58605647");
        txtTel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero Tel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(36, 36, 77))); // NOI18N
        panelBorder2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 160, 40));

        txtTotoal.setForeground(new java.awt.Color(36, 36, 77));
        txtTotoal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTotoal.setText("  58605647");
        txtTotoal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Montant Achat Totale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(36, 36, 77))); // NOI18N
        panelBorder2.add(txtTotoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, 40));

        txtdeposer.setForeground(new java.awt.Color(36, 36, 77));
        txtdeposer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtdeposer.setText("  58605647");
        txtdeposer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Montant Deposer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(36, 36, 77))); // NOI18N
        panelBorder2.add(txtdeposer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 160, 40));

        panelBorder3.add(panelBorder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 270, 460));

        panelBorder4.setBackground(new java.awt.Color(242, 141, 24));

        buttonBadges1.setBackground(new java.awt.Color(36, 36, 77));
        buttonBadges1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/close.png"))); // NOI18N
        buttonBadges1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder4Layout = new javax.swing.GroupLayout(panelBorder4);
        panelBorder4.setLayout(panelBorder4Layout);
        panelBorder4Layout.setHorizontalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder4Layout.createSequentialGroup()
                .addContainerGap(1004, Short.MAX_VALUE)
                .addComponent(buttonBadges1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBorder4Layout.setVerticalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonBadges1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBorder3.add(panelBorder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(242, 141, 24));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        panelBorder3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1050, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelBorder3, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panelBorder3, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBadges1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges1ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonBadges1ActionPerformed

    private void buttonBadges3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges3ActionPerformed
      calculer();
      Afficher();
    }//GEN-LAST:event_buttonBadges3ActionPerformed

    private void buttonBadges4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges4ActionPerformed
     Afficher();
     calculer();
     buttonBadges3.setVisible(true);
     buttonBadges4.setVisible(false);
    }//GEN-LAST:event_buttonBadges4ActionPerformed

  
    public static void main( int id) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menudetailer( id).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonBadges buttonBadges1;
    private swing.ButtonBadges buttonBadges3;
    private swing.ButtonBadges buttonBadges4;
    private swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.PanelBorder panelBorder2;
    private swing.PanelBorder panelBorder3;
    private swing.PanelBorder panelBorder4;
    private Menuclient.Table table1;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtTel;
    private javax.swing.JLabel txtTotoal;
    private javax.swing.JLabel txtdeposer;
    private javax.swing.JLabel txtnom;
    private javax.swing.JLabel txtreste;
    // End of variables declaration//GEN-END:variables
}
