/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Historie;

import Data.Achat;
import Data.TableAchat;
import Data.TableClient;
import Menuclient.TableActionCellEditor;
import Menuclient.TableActionCellRender;
import Menuclient.TableActionEvent;
import Modifier.Modifierachat;
import Supprimer.SupprimerAchat;
import Table.ScrollBar;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monta
 */
public class Historie extends javax.swing.JInternalFrame {

    /**
     * Creates new form Historie
     */
    void Table(){
     TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                 Modifierachat mo =new Modifierachat(table1.valusId(row),table1.valuspos1(row));
                mo.main(table1.valusId(row),table1.valuspos1(row));

              
            }

            @Override
            public void onDelete(int row) {
                if (table1.isEditing()) {
                    table1.getCellEditor().stopCellEditing();
                }
                SupprimerAchat  sup =new SupprimerAchat(table1.valusId(row),table1.valuspos1(row));
              sup.main(table1.valusId(row),table1.valuspos1(row));
                    
            }

            @Override
            public void onView(int row) {
                   jLabel1.setText("Achat "+table1.valusId(row));
                Achat ach =new Achat(table1.valusId(row),0.0,0.0,0.0,"",table1.valuspos1(row));
           table1.setModel(ach.Table2(table1.valusId(row), table1.valuspos1(row)));
           buttonBadges4.setVisible(true);
           buttonBadges3.setVisible(false);
            }
        };
       jScrollPane1.setVerticalScrollBar(new ScrollBar());
        jScrollPane1.getVerticalScrollBar().setBackground(Color.WHITE);
        jScrollPane1.getViewport().setBackground(new Color(36,36,77));
        JPanel p = new JPanel();
        p.setBackground(new Color(36,36,77));
        jScrollPane1.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
     
        String[] mod ={ "ID Achat","id Client" ,"Montant Totale","Montant Deposer","Montant Reste","Date Achat","Action"};
        DefaultTableModel model = new DefaultTableModel(null,mod); 
         TableAchat ach =new TableAchat(); 
          TableClient tabe =new TableClient();
        for ( Achat c : ach.getTable()) {
        model.addRow(new Object[]{c.getID_ACHAT(),c.getIdclient(),c.getMONTANT_TOTALE(), c.getMONTANT_DEPOSER(),c.getMONTENT_RESTE(),c.getDATE_ACHAT()});
        }
        table1.setModel(model);
         table1.getColumnModel().getColumn(6).setCellRenderer(new TableActionCellRender());
        table1.getColumnModel().getColumn(6).setCellEditor(new TableActionCellEditor(event));   
    
    
    }
    public Historie() {
        initComponents();
         buttonBadges4.setVisible(false);
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        setBackground(new Color (0,0,0,0));
       Table();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degrade1 = new swing.degrade();
        panelBorder2 = new swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new Menuclient.Table();
        jLabel1 = new javax.swing.JLabel();
        buttonBadges3 = new swing.ButtonBadges();
        buttonBadges4 = new swing.ButtonBadges();

        panelBorder2.setBackground(new java.awt.Color(36, 36, 77));
        panelBorder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        table1.setBackground(new java.awt.Color(36, 36, 77));
        table1.setForeground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table1.setOpaque(false);
        jScrollPane1.setViewportView(table1);

        panelBorder2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 960, 640));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 141, 24));
        jLabel1.setText("Menu Achat ");
        panelBorder2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        buttonBadges3.setBackground(new java.awt.Color(242, 141, 24));
        buttonBadges3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/refresh (1).png"))); // NOI18N
        buttonBadges3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges3ActionPerformed(evt);
            }
        });
        panelBorder2.add(buttonBadges3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 42, 36));

        buttonBadges4.setBackground(new java.awt.Color(242, 141, 24));
        buttonBadges4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/contour-du-bouton-circulaire-fleche-arriere-gauche.png"))); // NOI18N
        buttonBadges4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges4ActionPerformed(evt);
            }
        });
        panelBorder2.add(buttonBadges4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 42, 36));

        javax.swing.GroupLayout degrade1Layout = new javax.swing.GroupLayout(degrade1);
        degrade1.setLayout(degrade1Layout);
        degrade1Layout.setHorizontalGroup(
            degrade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(degrade1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        degrade1Layout.setVerticalGroup(
            degrade1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(degrade1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(degrade1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(degrade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBadges3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges3ActionPerformed
Table();
    }//GEN-LAST:event_buttonBadges3ActionPerformed

    private void buttonBadges4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges4ActionPerformed
        Table();
        buttonBadges3.setVisible(true);
        buttonBadges4.setVisible(false);
        jLabel1.setText("Menu Achat ");
    }//GEN-LAST:event_buttonBadges4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonBadges buttonBadges3;
    private swing.ButtonBadges buttonBadges4;
    private swing.degrade degrade1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.PanelBorder panelBorder2;
    private Menuclient.Table table1;
    // End of variables declaration//GEN-END:variables
}
